name: Remote SSH Command to update webserver

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ssh_stato_host }}
        username: ${{ secrets.ssh_strato_username }}
        password: ${{ secrets.ssh_strato_password }}
        port: 22
        script: |
          cd blom-de
          git pull
