name: Connect via SSH and pull latest GIT change

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Change directory and git pull
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ssh_stato_host }}
        username: ${{ secrets.ssh_strato_username }}
        password: ${{ secrets.ssh_strato_password }}
        port: 22
        script: |
          cd blom-de/
          git pull https://github.com/lennartblom/blom-de.git master
